name: scrollable_clean_calendar
description: A clean calendar widget with vertical scroll, locale, and range selection date
version: 1.4.1
homepage: https://github.com/FabioFiuza/scrollable_clean_calendar

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/